-- MySQL Script generated by MySQL Workbench
-- 01/19/17 12:26:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Film` (
  `id_Film` INT NOT NULL AUTO_INCREMENT,
  `Title` LONGTEXT NOT NULL,
  `Ganre` ENUM('ACTION', 'ADVENTURE', 'COMEDY', 'CRIME', 'DRAMA', 'HORROR', 'WESTERNS', 'WAR') NOT NULL,
  `Release_Date` DATE NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Film`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Stars` (
  `id_Stars` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MidleName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Date_of_Birth` DATE NULL,
  PRIMARY KEY (`id_Stars`),
  UNIQUE INDEX `LastName_UNIQUE` (`LastName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Films_Stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Films_Stars` (
  `id_Film` INT NOT NULL,
  `id_Stars` INT NOT NULL,
  INDEX `id_Stars` (`id_Stars` ASC),
  INDEX `id_Film` (`id_Film` ASC),
  CONSTRAINT `id_Stars`
    FOREIGN KEY (`id_Stars`)
    REFERENCES `library`.`Stars` (`id_Stars`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_Film`
    FOREIGN KEY (`id_Film`)
    REFERENCES `library`.`Film` (`id_Film`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`User` (
  `id_User` INT NOT NULL AUTO_INCREMENT,
  `First_Name` TEXT NULL,
  `Midle_Name` TEXT NULL,
  `Last_Name` varchar(80) NOT NULL,
  `Passwords` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  'Role' VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_User`),
  UNIQUE INDEX `Last_Name_UNIQUE` (`Last_Name` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Review` (
  `id_Review` INT NOT NULL AUTO_INCREMENT,
  `id_User` INT NOT NULL,
  `id_Film` INT NOT NULL,
  `Text` TEXT NOT NULL,
  `Mark` DOUBLE NOT NULL,
  PRIMARY KEY (`id_Review`),
  INDEX `id_Film` (`id_Film` ASC),
  INDEX `id_User` (`id_User` ASC),
  
    FOREIGN KEY (`id_Film`)
    REFERENCES `library`.`Film` (`id_Film`)
    ,
  
    FOREIGN KEY (`id_User`)
    REFERENCES `library`.`User` (`id_User`)
   )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE library;


INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Terminator 2: Judgment Day', 'ACTION', '1991-7-1', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Pirates of the Caribbean: The Curse of The Black Pear', 'ADVENTURE', '2003-6-28', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('The Mask', 'COMEDY', '1994-7-29', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('The Lord of the Rings: The Two Towers', 'ADVENTURE', '2002-12-18', 'UK');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Pulp Fiction', 'COMEDY', '1994-9-10', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Saw', 'HORROR', '2004-10-1', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Massaker', 'HORROR', '2010-01-01', 'BY');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('The Godfather', 'CRIME', '1972-3-14', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Titanic', 'DRAMA', '1997-10-18', 'USA');
INSERT INTO `library`.`film` (`Title`, `Ganre`, `Release_Date`, `Country`) VALUES ('Fight Club', 'DRAMA', '1999-9-10', 'USA');

INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Arnold', 'Alois', 'Schwarzenegger', '1947-7-30');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('John', 'Christopher', 'Depp', '1963-6-9');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('James', 'Eugene', 'Carrey', '1962-1-17');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Orlando', 'Jonathan', 'Bloom', '1977-1-13');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('John', 'Joseph', 'Travolta', '1954-2-18');
INSERT INTO `library`.`stars` (`FirstName`, `LastName`, `Date_of_Birth`) VALUES ('Leigh', 'Whannell', '1977-1-17');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Dmitry', 'Arturovich', 'Miller', '1972-4-2');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Alfredo', 'James', 'Pacino', '1940-4-25');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Leonardo', 'Wilhelm', 'DiCaprio', '1974-11-11');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Edward', 'Harrison', 'Norton', '1969-8-18');
INSERT INTO `library`.`stars` (`FirstName`, `MidleName`, `LastName`, `Date_of_Birth`) VALUES ('Brad', 'William', 'Pitt', '1963-12-18');

INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('1', '1');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('2', '2');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('3', '3');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('4', '4');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('5', '5');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('6', '6');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('7', '7');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('8', '8');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('9', '9');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('10', '10');
INSERT INTO `library`.`films_stars` (`id_Film`, `id_Stars`) VALUES ('10', '11');

INSERT INTO `library`.`library`.`User` (`First_Name`, `Midle_Name`, `Last_name`,`Passwords`,`Email`,`Role`) VALUES ('Admin', 'Admin', 'Admin','12345','Admin');
INSERT INTO `library`.`library`.`User` (`First_Name`, `Midle_Name`, `Last_name`,`Passwords`,`Email`,`Role`) VALUES ('User', 'User', 'User','12345','User');

